### ISSUE TITLE
kernel_task constantly at ~70%, fans running at max speed constantly

### ISSUE THREAD

**Issue by ericfjosne** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#7]
After testing the latest EFI (0.8.4), I can confirm that the kernel_task process is stagnating at 60% CPU usage constantly. This causes battery to drain fast and fans to kick it at full speed quite quickly.

This is an issue that was already elaborated upon in a separate repository: https://github.com/sambow23/Dell-XPS-13-7390-macOS/issues/17

We believe this to be thunderbolt related, but haven't been able to pinpoint this in a log entry yet.

**Comment by H3C4T0M8** [comment]
Sorry for late answer. I will check your infos soon. 

A way to fix (controll) cpu usage + cpu temperature maybe possible with different power management configurations with cpufriendfriend or ssdtPRGen.sh https://github.com/Piker-Alpha/ssdtPRGen.sh

i remeber to got a configuration for my i7 10510u with 39-40 degree in idle . the cpu % usage I don't have check.

Because the cpu fans... you have install windows and have select there different power options (one option, for silence fan  in Dell Power Manager https://www.dell.com/support/contents/de-de/article/product-support/self-support-knowledgebase/software-and-downloads/dell-power-manager - select one and make reboot. maybe it work when you don't make nvram reset in opencore.

feedbacks welcome!!!! 

And if you have more infos, or see a way to fix this problem, let me know.

**Comment by H3C4T0M8** [comment]
You have wait some minutes after you start the Hackintosh? Check the picture. 
![Bildschirm­foto 2022-11-25 um 13 04 14](https://user-images.githubusercontent.com/96039915/203983265-e9f1a660-cf5f-4869-9465-3eb40058e792.png)

**Comment by ericfjosne** [comment]
It stays this way even after a few hours unfortunately.

**Comment by H3C4T0M8** [comment]
> It stays this way even after a few hours unfortunately.

Nope.... At moment I try to make a new EFI. Check the pictures and how much % used ;-)

![Bildschirm­foto 2023-02-14 um 09 58 12](https://user-images.githubusercontent.com/96039915/218697718-71cbb04a-df13-47c1-948f-a78b674f3b23.png)
![Bildschirm­foto 2023-02-14 um 10 29 50](https://user-images.githubusercontent.com/96039915/218697770-a0bf2c34-44a8-4fdd-8396-487c753e3f87.png)

**Comment by ericfjosne** [comment]
That looks like a serious improvement 🎉 

Did you already create a branch on your repo where these changes were published?

**Comment by H3C4T0M8** [comment]
At moment I don't finished. with Catalina you can get sound with https://sourceforge.net/projects/voodoohda/ . I need to speak with MacPeet because the AppleALC have read something that the layout make the cpu issue.
You can test it...disable AppleALC and check if processor usage better.

I will upload it in the next days... if it finished, or not.

**Comment by H3C4T0M8** [comment]
https://osxlatitude.com/forums/topic/5907-manually-controlling-the-cooling-fan-of-a-dell-laptop-or-pc/ if it work?  I will test it in the next days ... but I don't think so

**Comment by H3C4T0M8** [comment]
I am not finished...but here a efi to test.
![Bildschirmfoto 2023-03-05 um 01 59 12](https://user-images.githubusercontent.com/96039915/222936298-dbaedf5c-f0fd-420d-a277-9c51a3a2eac2.png)

https://files.fm/f/zx8stpyf9

**Comment by H3C4T0M8** [comment]
TRY to test this NEW EFI, to give me feedback !!!

https://files.fm/u/f2a3tb2ee

**Comment by H3C4T0M8** [comment]
I will close this thread now... kernel_task issue fixed with new kexts. my laptop run with around 43-46 degrees in idle mode. thx

**Comment by ericfjosne** [comment]
Hey @H3C4T0M8 ! Thanks a lot for this. I am not able to test at the moment, but will update here when I get the chance. Can you please highlight what the actual fix was? Was it Thunderbolt related or something else?

**Comment by H3C4T0M8** [comment]
@ericfjosne MacPeet created a new AppleALC.kext. ( 2 versions here on my GitHub folder... one of them need codecommander, the other version don't need codecommander. ( Only Internal speakers and Mic work )The kext fix the hot cpu problem + the kernel_task need only 1-3 % CPU used. The FAN don't work much now too.
