### ISSUE TITLE
we cannot update Lilu.kext?

### ISSUE THREAD

**Issue by irfanhutomo2** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#8]
newer lilu is release, can i update the kext?

**Comment by H3C4T0M8** [comment]
Long time not work with the Dell Laptop. I think you can update it. when you lose the sound, you can copy the old kext back into the kext folder.
At moment I work on a new efi. The AppleALC.kext don't work good. Because this the cpu to hot.

Today the temperature from cpu + the System Prozess task looks much better.
![Bildschirm­foto 2023-02-14 um 09 58 12](https://user-images.githubusercontent.com/96039915/218696382-4edc580b-cceb-4b7e-9756-28ee34fe9ba9.png)
![Bildschirm­foto 2023-02-14 um 10 29 50](https://user-images.githubusercontent.com/96039915/218696433-17c0e6a8-8536-458f-a3d8-bb2c06b2a1f9.png)

But need to check how I can fix the problem with AppleALC.kext. with Catalina no problem... there we can switch to VoodooHDA.kext

If you like to test the EFI, let me know. ( at moment not finished )

**Comment by irfanhutomo2** [comment]
i want

**Comment by irfanhutomo2** [comment]
with VoodooHDA are combo jack work?

**Comment by H3C4T0M8** [comment]
bro...test this efi please...let me know if it fix the cpu problem. thx 

https://files.fm/u/f2a3tb2ee
